# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c9585a444e41b553ac46c6d7f4eb38ae03d4133f57b74bd48b67f5dcc5fe7bd1583951a0dfc5da28570d16db0eca0f359eac0df82165dc625aa7075cd91cf0a

test:
  secret_key_base: 81b027741ed9a549cab021a611bab2201ea2a859092cf9bd5630d5aa445367ad200eeda9f77876c9c11e83323de9269a6f4e546360b3edec2ba7cd1a2fe7a40c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
